### ISSUE TITLE
PS5BOT.PY Scrape

### ISSUE THREAD

**Issue by TheManWhoLikesToCode** [VVNoodle/PS5bot#13]
Sorry for making another issue. I've completed all of steps to install the program. I've added a image to help troubleshooting.
![troubleshooting](https://user-images.githubusercontent.com/74679492/99584737-595bb800-29b3-11eb-9858-6e8ffe13e7fb.PNG)

It seems to be a forever loop. Nothing happens no pages open no prompts pop up

**Comment by MatteoBeckr** [comment]
Hey there, 
I am VERY new to coding as well as GitHub and found myself just wanting to try and using a bot myself for once to kind of better my odds at getting a ps5 myself. 
but I was wondering, the Walmart website for instance allows a "pre-entering" of all the data so checkout goes merely with a couple clicks as far as I saw, leaving entering of cc data as well as address,s etc. into the bot useless, so would there be a way to skip over that part with this one since I just kinda felt like it leaves me open to identity theft n stuff :S 
thanks!

**Comment by texastoastt** [comment]
This is not written in Python, so adding a .py file extension will only make this worse. Revert any changes you have made and use the following command: 

node ps5bot scrape

**Comment by TheManWhoLikesToCode** [comment]
Thank you so much man I really appreciate the help. This is my first time on Github and I tried to listen to the people it was working for lesson learned.

10/10 I love you
